import Head from 'next/head'

const Home = () => (
  <div>
    <Head>
      <title>NFT Marketplace</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className="text-3xl font-bold underline">NFT Marketplace</div>
  </div>
)
export default Home
